#!/usr/bin/perl

# Wrap check-aliases.tlu
#
# Manuel Pégourié-Gonnard, 2010. WTFPL v2.

my $usage = <<USAGE;
Usage: $0 [--td=texdoc-path] [--tl=texlive_path]
USAGE

use warnings;
use strict;
use utf8;
use open qw(:std utf8);

BEGIN { (my $dir = $0) =~ s!(.*)/.*!$1!; unshift @INC, $dir; }
use TdTools;

my $conf = TdTools::setup($usage);

exec "texlua $conf->{texdoc_path}/tools/check-aliases.tlu";

__END__
