#!/usr/bin/env perl
# $Id$
# Start a shell or run command with the TdTools environment
#
# Manuel Pégourié-Gonnard, 2010-2018. WTFPL v2.

my $usage = <<USAGE;
Usage: $0 [--td=texdoc-path] [--tl=texlive_path] [-- command]
USAGE

use warnings;
use strict;
use utf8;
use open qw(:std utf8);

BEGIN { (my $dir = $0) =~ s!(.*)/.*!$1!; unshift @INC, $dir; }
use TdTools;

my $conf = TdTools::setup($usage);

unshift @ARGV, $ENV{SHELL} || '/bin/sh' unless @ARGV;
exec @ARGV;

__END__
