#!/bin/bash -eu

# Run tests on Travis CI
#
# Public domain.

if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
  TLBIN=$HOME/texlive/bin/x86_64-darwin
else
  TLBIN=$HOME/texlive/bin/x86_64-linux
fi

./tools/test-basic --tl=$TLBIN --td=.
